/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppIcon: typeof import('./src/components/AppIcon.vue')['default']
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    CommentTree: typeof import('./src/components/CommentTree.vue')['default']
    Empty: typeof import('./src/components/Empty.vue')['default']
    LoginGuide: typeof import('./src/components/LoginGuide.vue')['default']
    PostCard: typeof import('./src/components/PostCard.vue')['default']
    PostList: typeof import('./src/components/PostList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SegTabs: typeof import('./src/components/SegTabs.vue')['default']
    VanActionSheet: typeof import('vant/es')['ActionSheet']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
